export const LOCATION = "G3TD3R_LOCATION";
export const REQUEST = "G3TD3R_REQUEST";
export const ACCESS_TOKEN = "G3TD3R_ACC3SS_T0K3N";
export const USER = "G3TD3R_US3R";
export const CAR_TYPES = "G3TD3R_CAR_TYP3S";
export const NEGOTIATION = "G3TD3R_N3G0T!ATION";

export const TRIGGERS = {
  NEW_REQUEST: "NEW_REQUEST",
  NEW_NEGOTIATION: "NEW_NEGOTIATION",
  NEGOTIATION_UPDATE: "NEGOTIATION_UPDATE",
};
